### ISSUE TITLE
What is types column in participants table?

### ISSUE THREAD

**Issue by huunovahub** [eyoosuf/Messenger#10]
Can you explain types column in participants table using for what? Can you list enum values of this. Thanks

**Comment by yoosuf** [comment]
that is to define what is the type pf chat, perhaps like a label

**Comment by trankhacvy** [comment]
@yoosuf Should we define this type in **Conversation** table. I mean when a user chat 1 x 1 (type = single) and when he/she chats on a group (type = group), **type** should be define in **Conversation**, right ?
