### ISSUE TITLE
Identifying duplicate conversations

### ISSUE THREAD

**Issue by twigs67** [eyoosuf/Messenger#14]
Interesting db design. I'm curious though, do you create a ```conversation.id``` once, say **user A** selects **user B** to have a conversation with? Or do you only create the ```conversation.id``` once a message is exchanged between the two?

**Comment by jamesrenaudcode** [comment]
Thanks! I am planning to create the id once the message is exchanged

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yoosuf** [comment]
@twigs67 Good one, will work around and do a fix  ASAP, if you have a solution please send a pull request
