### ISSUE TITLE
Participants table: Add unique index on conversation_id and user_id

### ISSUE THREAD

**Issue by nayaabkhan** [eyoosuf/Messenger#17]
We could add a `UNIQUE` constraint to avoid adding the same user on the same conversation multiple times. Let me know what you think.

Happy to provide a PR if you agree.

**Comment by yoosuf** [comment]
@nayaabkhan can you send a PR

**Comment by nayaabkhan** [comment]
@yoosuf Done [here](https://github.com/yoosuf/Messenger/pull/18).
