### ISSUE TITLE
Adds support for unread counts and ordering strategy

### ISSUE THREAD

**Issue by orfeapapa** [eyoosuf/Messenger#19]
Would be nice to document the unread count and ordering query strategies in the repo.

**Comment by yoosuf** [comment]
The count and order no need to be on database, you can use order by (id, date)  desc or asc, additionally having an order would be nice to have column, and you can add it as you required to have custom sorting

you can do the count programmatically easily

**Comment by orfeapapa** [comment]
@yoosuf  My concern was about queries like: give me the conversations between user a and user b
