### ISSUE TITLE
Should we define `type` in `conversation` table instead of `participants`?

### ISSUE THREAD

**Issue by purrion** [eyoosuf/Messenger#22]
@yoosuf Should we define this type in **Conversation** table. I mean when a user chat 1 x 1 (type = single) and when he/she chats on a group (type = group), **type** should be define in **Conversation**, right ?

_Originally posted by @trankhacvy in https://github.com/yoosuf/Messenger/issues/10#issuecomment-823758106_
      
I have the same question with this guy.
In current version, we can encounter the case that two (or more) records have a same  `conversation_id` but different `type`. So how can we avoid it?

**Comment by yoosuf** [comment]
@datleviet can you send a PR
