### ISSUE TITLE
participants_id in messages

### ISSUE THREAD

**Issue by bring2dip** [eyoosuf/Messenger#4]
I am confused about two things in the deisgn
1. Why have you included participants_id in messages table? If a message belongs to conversation then the participants can be know from it.
2. why have you made the `type`(single, group) in participants table instead of conversation?

**Comment by yoosuf** [comment]
@bring2dip good shout, I cannot recall why I have done such way, but the new change make more sense.

You can also send pull request if you think there need to be done changes or improvements, I am more than happy to review and merge them.

**Comment by yoosuf** [comment]
Additionally the participants table has the `type` to limit the number of associated users based on the type
