### ISSUE TITLE
Create new Feature for this database

### ISSUE THREAD

**Issue by jackphuongvu** [eyoosuf/Messenger#6]
I see your database schema is really great and I think it will help me a lot to build a Chat App. However, I still want to custom it for some of my own ideas. So basically, right now I just want to do this thing like this.

- There are lots of Topics in my App like Friends, Family, ... (So each Topic will have ID, Name as well)
- So when they join into my Chat Room, I show for them lots of those Topics
- After they hit to join talking about one Topic, I show for them lots of other users in that Topic Room
- In that Topic room, they can choose any people to talk with (just one for now)
- For now, I just support for them chat between one user and one user.

I'm still lack of my knowledge about building this thing so it will be good if someone can help a while with this cool idea.
Thanks a lot for your time.

**Comment by yoosuf** [comment]
@lunvjp it sounds a good idea, we should talk privately about it, please send me a message at https://www.finetick.com
