### ISSUE TITLE
I found some weird properties inside your Schema

### ISSUE THREAD

**Issue by jackphuongvu** [eyoosuf/Messenger#7]
Can you please create a Docs about these things so that other people can understand easily?

**`messages` table**
-----------------
![image](https://user-images.githubusercontent.com/23715737/47265830-f0957d80-d557-11e8-87b2-4c6eb4324a9d.png)
- `guid`
- `sender_id`: 
+ sender_id: user id of the person sending out the chat
- `attachment_thumb_url`
- `attachment_url`
**

**Comment by yoosuf** [comment]
sure will try to do that

**Comment by nayaabkhan** [comment]
Hello, kudos for your effort @yoosuf! I am in the process of designing a schema for a chat system myself and this is a great reference.

I'd like to dig in more into the DOC requested by the original poster. But it seems I missed it. Can you point me where I can find it?

Basically I am wondering about the use-case where one would need to use `guid`. Perhaps for URLs?
